Replace __thread with thread_local
Signed-off-by: Lukasz Dorau <lukasz.dorau@intel.com>

diff --git a/.github/workflows/basic.yml b/.github/workflows/basic.yml
--- a/.github/workflows/basic.yml
+++ b/.github/workflows/basic.yml
@@ -3,95 +3,6 @@ name: GitHubActions
 on: [push, pull_request]
 
 jobs:
-  ubuntu-build:
-    name: Build - Ubuntu
-    
-    strategy:
-      matrix:
-        os: ['ubuntu-20.04', 'ubuntu-22.04']
-        build_type: [Debug, Release]
-        compiler: [{c: gcc, cxx: g++}]
-        pool_tracking: ['-DUMF_ENABLE_POOL_TRACKING=ON', '-DUMF_ENABLE_POOL_TRACKING=OFF']
-        include:
-          - os: 'ubuntu-20.04'
-            build_type: Release
-            compiler: {c: gcc-7, cxx: g++-7}
-          - os: 'ubuntu-22.04'
-            build_type: Release
-            compiler: {c: clang, cxx: clang++}
-    runs-on: ${{matrix.os}}
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        
-      - name: Install apt packages
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y clang cmake libnuma-dev
-      
-      - name: Install g++-7
-        if: matrix.compiler.cxx == 'g++-7'
-        run: |
-          sudo apt-get install -y ${{matrix.compiler.cxx}}
-
-      - name: Configure build
-        run: >
-          cmake
-          -B ${{github.workspace}}/build
-          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
-          -DCMAKE_C_COMPILER=${{matrix.compiler.c}}
-          -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
-          -DUMF_FORMAT_CODE_STYLE=OFF
-          -DUMF_DEVELOPER_MODE=ON
-          ${{matrix.pool_tracking}}
-
-      - name: Build UMF
-        run: |
-          cmake --build ${{github.workspace}}/build -j $(nproc)
-          
-      - name: Run tests
-        working-directory: ${{github.workspace}}/build
-        run: |
-          ctest --output-on-failure
-
-  windows-build:
-    name: Build - Windows
-    strategy:
-      matrix:
-        os: ['windows-2019', 'windows-2022']
-        build_type: [Debug, Release]
-        compiler: [{c: cl, cxx: cl}]
-        pool_tracking: ['-DUMF_ENABLE_POOL_TRACKING=ON', '-DUMF_ENABLE_POOL_TRACKING=OFF']
-        include:
-          - os: 'windows-2022'
-            build_type: Release
-            compiler: {c: clang-cl, cxx: clang-cl}
-            pool_tracking: -DUMF_ENABLE_POOL_TRACKING=ON
-            toolset: "-T ClangCL"
-    runs-on: ${{matrix.os}}
-
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Configure build
-        run: >
-          cmake
-          -B ${{github.workspace}}/build
-          ${{matrix.toolset}}
-          -DCMAKE_C_COMPILER=${{matrix.compiler.c}}
-          -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
-          -DUMF_FORMAT_CODE_STYLE=OFF
-          -DUMF_DEVELOPER_MODE=ON
-          ${{matrix.pool_tracking}}
-
-      - name: Build UMF
-        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} -j $Env:NUMBER_OF_PROCESSORS
-
-      - name: Test
-        working-directory: ${{github.workspace}}/build
-        run: ctest -C ${{matrix.build_type}} --output-on-failure
-
   macos-build:
     name: Build - MacOS
     strategy:
@@ -101,6 +12,13 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+
+      - name: Install brew packages
+        run: |
+          find /usr/ -name threads.h || echo "threads.h not found!"
+          brew install libc6-dev || echo "libc6-dev not found!"
+          brew install libccd || echo "libccd not found!"
+          find /usr/ -name threads.h
 
       - name: Install Python requirements
         run: python3 -m pip install -r third_party/requirements.txt
